apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T11:17:51Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-32cff8fa-18e3-11ea-94c4-42010a9c0043
    resourceVersion: "493887"
    selfLink: /api/v1/persistentvolumes/pvc-32cff8fa-18e3-11ea-94c4-42010a9c0043
    uid: 34d6f3cc-18e3-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: mysql-pv-claim
      namespace: user123
      resourceVersion: "493865"
      uid: 32cff8fa-18e3-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-32cff8fa-18e3-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T12:37:08Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-46d5ea39-18ee-11ea-94c4-42010a9c0043
    resourceVersion: "513536"
    selfLink: /api/v1/persistentvolumes/pvc-46d5ea39-18ee-11ea-94c4-42010a9c0043
    uid: 48b20eda-18ee-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: datadir-kafka-0
      namespace: user111
      resourceVersion: "513520"
      uid: 46d5ea39-18ee-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-46d5ea39-18ee-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T12:08:35Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-494897e7-18ea-11ea-94c4-42010a9c0043
    resourceVersion: "506405"
    selfLink: /api/v1/persistentvolumes/pvc-494897e7-18ea-11ea-94c4-42010a9c0043
    uid: 4b5c06c4-18ea-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: fortune-claim
      namespace: user175
      resourceVersion: "506296"
      uid: 494897e7-18ea-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-494897e7-18ea-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T13:28:04Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-63abc272-18f5-11ea-94c4-42010a9c0043
    resourceVersion: "526057"
    selfLink: /api/v1/persistentvolumes/pvc-63abc272-18f5-11ea-94c4-42010a9c0043
    uid: 65b3c5ca-18f5-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-logstash-0
      namespace: user111
      resourceVersion: "526022"
      uid: 63abc272-18f5-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-63abc272-18f5-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T13:28:04Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-63e01d65-18f5-11ea-94c4-42010a9c0043
    resourceVersion: "526063"
    selfLink: /api/v1/persistentvolumes/pvc-63e01d65-18f5-11ea-94c4-42010a9c0043
    uid: 65cdea9e-18f5-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: prometheus-config-prometheus-0
      namespace: user111
      resourceVersion: "526033"
      uid: 63e01d65-18f5-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-63e01d65-18f5-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T13:28:04Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-63e0a660-18f5-11ea-94c4-42010a9c0043
    resourceVersion: "526068"
    selfLink: /api/v1/persistentvolumes/pvc-63e0a660-18f5-11ea-94c4-42010a9c0043
    uid: 65f127fa-18f5-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: prometheus-data-prometheus-0
      namespace: user111
      resourceVersion: "526037"
      uid: 63e0a660-18f5-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-63e0a660-18f5-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T11:12:50Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-7f26818d-18e2-11ea-94c4-42010a9c0043
    resourceVersion: "492613"
    selfLink: /api/v1/persistentvolumes/pvc-7f26818d-18e2-11ea-94c4-42010a9c0043
    uid: 8159ef77-18e2-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: redis-data-my-release-redis-slave-0
      namespace: user121play
      resourceVersion: "492579"
      uid: 7f26818d-18e2-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-7f26818d-18e2-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T11:12:49Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-7f2cfd55-18e2-11ea-94c4-42010a9c0043
    resourceVersion: "492609"
    selfLink: /api/v1/persistentvolumes/pvc-7f2cfd55-18e2-11ea-94c4-42010a9c0043
    uid: 81589a4e-18e2-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: redis-data-my-release-redis-master-0
      namespace: user121play
      resourceVersion: "492585"
      uid: 7f2cfd55-18e2-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-7f2cfd55-18e2-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T11:13:27Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-960be151-18e2-11ea-94c4-42010a9c0043
    resourceVersion: "492804"
    selfLink: /api/v1/persistentvolumes/pvc-960be151-18e2-11ea-94c4-42010a9c0043
    uid: 97fa9543-18e2-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: redis-data-my-release-redis-slave-1
      namespace: user121play
      resourceVersion: "492782"
      uid: 960be151-18e2-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-960be151-18e2-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T12:25:09Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-9a0cd85f-18ec-11ea-94c4-42010a9c0043
    resourceVersion: "510513"
    selfLink: /api/v1/persistentvolumes/pvc-9a0cd85f-18ec-11ea-94c4-42010a9c0043
    uid: 9c20c61b-18ec-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: elastic-data-elasticsearch-0
      namespace: user111
      resourceVersion: "510497"
      uid: 9a0cd85f-18ec-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-9a0cd85f-18ec-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T12:41:11Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-d7405604-18ee-11ea-94c4-42010a9c0043
    resourceVersion: "514573"
    selfLink: /api/v1/persistentvolumes/pvc-d7405604-18ee-11ea-94c4-42010a9c0043
    uid: d9360b6d-18ee-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: datadir-kafka-1
      namespace: user111
      resourceVersion: "514552"
      uid: d7405604-18ee-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-d7405604-18ee-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: gce-pd-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
    creationTimestamp: "2019-12-07T12:41:53Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      failure-domain.beta.kubernetes.io/region: europe-west3
      failure-domain.beta.kubernetes.io/zone: europe-west3-b
    name: pvc-f03b1ba3-18ee-11ea-94c4-42010a9c0043
    resourceVersion: "514762"
    selfLink: /api/v1/persistentvolumes/pvc-f03b1ba3-18ee-11ea-94c4-42010a9c0043
    uid: f225cf0d-18ee-11ea-94c4-42010a9c0043
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: datadir-kafka-2
      namespace: user111
      resourceVersion: "514737"
      uid: f03b1ba3-18ee-11ea-94c4-42010a9c0043
    gcePersistentDisk:
      fsType: ext4
      pdName: gke-workshop-c8985e2f--pvc-f03b1ba3-18ee-11ea-94c4-42010a9c0043
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - europe-west3-b
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - europe-west3
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
